{
 "title": "Memory Overview",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds, node_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{node_name=~\"$host\"}) without(job) - \n(max(node_memory_MemFree_bytes{node_name=~\"$host\"}) without(job) + \nmax(node_memory_Buffers_bytes{node_name=~\"$host\"}) without(job) + \n(max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached_bytes{node_name=~\"$host\",job=\"rds-basic\"}) without (job)))",
     "legendFormat": "Used"
    },
    {
     "expr": "max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-basic\"}) without (job)",
     "legendFormat": "Cached"
    },
    {
     "expr": "max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[5m])",
     "legendFormat": "Free"
    },
    {
     "expr": "max_over_time(node_memory_Buffers_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Buffers_bytes{node_name=~\"$host\"}[5m])",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Free Memory Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemFree_bytes{node_name=~\"$host\"}[5m])) * 100 /\n(max_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_MemTotal_bytes{node_name=~\"$host\"}[$interval]))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "VMM Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pages Size",
     "type": "graph",
     "description": "**Inactive** - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes\n\n**Active** - Memory that has been used more recently and usually not reclaimed unless absolutely necessary",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Inactive_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_Inactive_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Inactive "
      },
      {
       "expr": "max_over_time(node_memory_Active_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_Active_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Active "
      }
     ]
    },
    {
     "title": "Anonymous Memory Size",
     "type": "graph",
     "description": "**Inactive** Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)\n\n**Active**  Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Active_anon_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Active_anon_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Active"
      },
      {
       "expr": "max_over_time(node_memory_Inactive_anon_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Inactive_anon_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "File Cache Memory Size",
     "type": "graph",
     "description": "**Inactive**  File-backed memory on inactive LRU list\n\n**Active** File-backed memory on active LRU list",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Inactive_file_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Inactive_file_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Inactive"
      },
      {
       "expr": "max_over_time(node_memory_Active_file_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Active_file_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      },
      {
       "expr": "(rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096) + \n(rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[$interval]) - max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[5m]) - max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Used"
      },
      {
       "expr": "max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Free"
      },
      {
       "expr": "max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage Types",
     "type": "graph",
     "description": "**PageTables**  Memory used to map between virtual and physical memory addresses\n\n**AnonPages** Non-file backed pages mapped into userspace page tables\n\n**SwapCache**  Memory that keeps track of pages that have been fetched from swap but not yet been modified\n\n**Slab**  Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)\n\n**Swap**  Swap space used\n\n**Harware Corrupted** Amount of RAM that the kernel identified as corrupted / not working\n\n**Mapped** Files which have been mmaped, such as libraries\n\n**Dirty** Memory which is waiting to get written back to the disk\n\n**Writeback** Memory which is actively being written back to the disk\n\n**WritebackTmp** Memory used by FUSE for temporary writeback buffers\n\n**Shmem** Total memory used by shared memory (shmem) and tmpfs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_PageTables_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_PageTables_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "PageTables "
      },
      {
       "expr": "max_over_time(node_memory_SwapCached_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_SwapCached_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "SwapCached"
      },
      {
       "expr": "max_over_time(node_memory_Slab_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Slab_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Slab "
      },
      {
       "expr": "max_over_time(node_memory_SwapTotal_bytes{node_name=~\"$host\"}[$interval]) - max_over_time(node_memory_SwapFree_bytes{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Swap "
      },
      {
       "expr": "max_over_time(node_memory_HardwareCorrupted_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HardwareCorrupted_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Harware Corrupted "
      },
      {
       "expr": "max_over_time(node_memory_Mapped_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Mapped_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Mapped"
      },
      {
       "expr": "max_over_time(node_memory_Dirty_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Dirty_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dirty"
      },
      {
       "expr": "max_over_time(node_memory_Writeback_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Writeback_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Writeback"
      },
      {
       "expr": "max_over_time(node_memory_Shmem_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Shmem_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Shmem"
      },
      {
       "expr": "max_over_time(node_memory_AnonPages_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_AnonPages_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "AnonPages"
      },
      {
       "expr": "max_over_time(node_memory_Writeback_bytesTmp_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Writeback_bytesTmp_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "WritebackTmp"
      }
     ]
    },
    {
     "title": "Vmalloc",
     "type": "graph",
     "description": "**Total** total size of vmalloc memory area\n\n**Used** amount of vmalloc area which is used\n\n**Chunk** largest contiguous block of vmalloc area which is free",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{node_name=~\"$host\"}",
       "legendFormat": "Chunk"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{node_name=~\"$host\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{node_name=~\"$host\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Shared Memory",
     "type": "graph",
     "description": "**Total** Memory used by shared memory (shmem) and tmpfs\n\n**HugePages** Memory used by shared memory (shmem) and tmpfs allocated with huge pages\n\n**PmdMapped**  Shared memory mapped into userspace with huge pages",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Shmem_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Shmem_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      },
      {
       "expr": "max_over_time(node_memory_Shmem_bytesHugePages{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Shmem_bytesHugePages{node_name=~\"$host\"}[5m])",
       "legendFormat": "HugePages"
      },
      {
       "expr": "max_over_time(node_memory_Shmem_bytesPmdMapped{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Shmem_bytesPmdMapped{node_name=~\"$host\"}[5m])",
       "legendFormat": "PmdMapped"
      }
     ]
    },
    {
     "title": "Kernel Memory Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_KernelStack_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_KernelStack_bytes{node_name=~\"$host\"}[5m]) ",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "**Committed_AS**  Amount of memory presently allocated on the system\n\n**CommitLimit**  Amount of  memory currently available to be allocated on the system",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Committed_AS_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_Committed_AS_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Committed_AS"
      },
      {
       "expr": "max_over_time(node_memory_CommitLimit_bytes{node_name=~\"$host\"}[$interval]) or\nmax_over_time(node_memory_CommitLimit_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "CommitLimit"
      }
     ]
    },
    {
     "title": "Non-file Backed Pages Size",
     "type": "graph",
     "description": "**AnonPages** Non-file backed pages mapped into userspace page tables\n\n**AnonHugePages** Non-file backed huge pages mapped into userspace page tables",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_AnonHugePages_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_AnonHugePages_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "AnonHugePages"
      },
      {
       "expr": "max_over_time(node_memory_AnonPages_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_AnonPages_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "AnonPages"
      }
     ]
    },
    {
     "title": "Kernel Cache",
     "type": "graph",
     "description": "**Slab** in-kernel data structures cache\n**SReclaimable** Part of Slab, that might be reclaimed, such as caches\n **SUnreclaim** Part of Slab, that cannot be reclaimed on memory pressure",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Slab_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Slab_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      },
      {
       "expr": "max_over_time(node_memory_SReclaimable_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_SReclaimable_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "SReclaimable"
      },
      {
       "expr": "max_over_time(node_memory_SUnreclaim_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_SUnreclaim_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "SUnreclaim"
      }
     ]
    },
    {
     "title": "DirectMap Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_DirectMap1G_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_DirectMap1G_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Page Size 1G"
      },
      {
       "expr": "max_over_time(node_memory_DirectMap2M_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_DirectMap2M_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Page Size 2M"
      },
      {
       "expr": "max_over_time(node_memory_DirectMap4k_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_DirectMap4k_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Page Size 4K"
      }
     ]
    },
    {
     "title": "Bounce Memory",
     "type": "graph",
     "description": "**Bounce** Memory used for block device \"bounce buffers\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Bounce_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Bounce_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "NFS Pages Size",
     "type": "graph",
     "description": "**NFS_Unstable** NFS pages sent to the server, but not yet committed to stable storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_NFS_Unstable_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_NFS_Unstable_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "NFS Unstable"
      }
     ]
    },
    {
     "title": "Unevictable/MLocked Memory",
     "type": "graph",
     "description": "**Unevictable** Amount of unevictable memory that can't be swapped out for a variety of reasons\n\n**MLocked** Size of pages locked to memory using the mlock() system call",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_Unevictable_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Unevictable_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Unevictable"
      },
      {
       "expr": "max_over_time(node_memory_Mlocked_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Mlocked_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "MLocked"
      }
     ]
    },
    {
     "title": "Huge Pages Size",
     "type": "graph",
     "description": "**HugePages** Total size of the pool of huge pages\n\n**Hugepagesize**  Huge Page size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_HugePages_Total{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HugePages_Total_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "HugePages"
      },
      {
       "expr": "max_over_time(node_memory_Hugepagesize_bytes{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_Hugepagesize_bytes{node_name=~\"$host\"}[5m])",
       "legendFormat": "Hugepagesize "
      }
     ]
    },
    {
     "title": "HugePages Statistic",
     "type": "graph",
     "description": "**Total** Number of hugepages being allocated by the kernel (Defined with vm.nr_hugepages)\n\n**Free** The number of hugepages not being allocated by a process\n\n**Surp**  The number of hugepages in the pool above the value in vm.nr_hugepages. The maximum number of surplus hugepages is controlled by vm.nr_overcommit_hugepages.\n\n**Rsvd**  The number of  huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_memory_HugePages_Free{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HugePages_Free{node_name=~\"$host\"}[5m])",
       "legendFormat": "Free"
      },
      {
       "expr": "max_over_time(node_memory_HugePages_Rsvd{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HugePages_Rsvd{node_name=~\"$host\"}[5m])",
       "legendFormat": "Reserved"
      },
      {
       "expr": "max_over_time(node_memory_HugePages_Surp{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HugePages_Surp{node_name=~\"$host\"}[5m])",
       "legendFormat": "Surplus"
      },
      {
       "expr": "max_over_time(node_memory_HugePages_Total{node_name=~\"$host\"}[$interval]) or max_over_time(node_memory_HugePages_Total{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Number and Dynamic of Pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_vmstat_nr_free_pages{node_name=~\"$host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "rate(node_vmstat_pgactivate{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Activated"
      },
      {
       "expr": "rate(node_vmstat_pgdeactivate{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Deactivated"
      }
     ]
    },
    {
     "title": "IO activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Cache Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_active_file{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_active_file{node_name=~\"$host\"}[5m])",
       "legendFormat": "Active"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_inactive_file{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_inactive_file{node_name=~\"$host\"}[5m])",
       "legendFormat": "Inactive"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_isolated_file{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_isolated_file{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Isolated"
      }
     ]
    },
    {
     "title": "Anonymous Memory Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_active_anon{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_active_anon{node_name=~\"$host\"}[5m])",
       "legendFormat": "Active"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_inactive_anon{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_inactive_anon{node_name=~\"$host\"}[5m])",
       "legendFormat": "Inactive"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_isolated_anon{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_isolated_anon{node_name=~\"$host\"}[$interval])",
       "legendFormat": "Isolated"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_anon_transparent_hugepages{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_anon_transparent_hugepages{node_name=~\"$host\"}[5m])",
       "legendFormat": "Transparent Huge Pages"
      }
     ]
    },
    {
     "title": "Shmem Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_shmem{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_shmem{node_name=~\"$host\"}[5m])",
       "legendFormat": "Pages"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_shmem_hugepages{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_shmem_hugepages{node_name=~\"$host\"}[5m])",
       "legendFormat": "Hugepages"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_shmem_pmdmapped{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_shmem_pmdmapped{node_name=~\"$host\"}[5m])",
       "legendFormat": "Pmdmapped"
      }
     ]
    },
    {
     "title": "Dirty Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_dirty{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_dirty{node_name=~\"$host\"}[5m ])",
       "legendFormat": "Total"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_dirty_threshold{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_dirty_threshold{node_name=~\"$host\"}[5m])",
       "legendFormat": "Threshold"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_dirty_background_threshold{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_dirty_background_threshold{node_name=~\"$host\"}[5m])",
       "legendFormat": "Threshold (Backgroud)"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_writeback{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_writeback{node_name=~\"$host\"}[5m ])",
       "legendFormat": "Writeback"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_unstable{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_unstable{node_name=~\"$host\"}[5m ])",
       "legendFormat": "Unstable"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_writeback_temp{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_writeback_temp{node_name=~\"$host\"}[5m ])",
       "legendFormat": "Writeback (Temporary )"
      }
     ]
    },
    {
     "title": "Pages Allocated to Page Tables",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_page_table_pages{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_page_table_pages{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Bounce Buffer Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_bounce{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_bounce{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Misc Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_free_cma{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_free_cma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Free Contiguous"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_vmscan_write{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_vmscan_write{node_name=~\"$host\"}[5m])",
       "legendFormat": "Written by VM scanner"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_vmscan_immediate_reclaim{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_vmscan_immediate_reclaim{node_name=~\"$host\"}[5m])",
       "legendFormat": "Immediately Reclaimed"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_unevictable{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_unevictable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Unevictable"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_mlock{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_mlock{node_name=~\"$host\"}[5m])",
       "legendFormat": "Mlock"
      }
     ]
    },
    {
     "title": "Pages Mapped by Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_mapped{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_mapped{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Kernel Stack Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_kernel_stack{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_kernel_stack{node_name=~\"$host\"}[5m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Slab Pages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "max_over_time(node_vmstat_nr_slab_reclaimable{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_slab_reclaimable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Reclaimable"
      },
      {
       "expr": "max_over_time(node_vmstat_nr_slab_unreclaimable{node_name=~\"$host\"}[$interval]) or max_over_time(node_vmstat_nr_slab_unreclaimable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Unreclaimable"
      },
      {
       "expr": "rate(node_vmstat_slabs_scanned{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_slabs_scanned{node_name=~\"$host\"}[5m])",
       "legendFormat": "Scanned"
      },
      {
       "expr": "rate(node_vmstat_drop_slab{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_drop_slab{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dropped"
      }
     ]
    }
   ]
  },
  {
   "title": "Pages per Zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgalloc_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgalloc_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgalloc_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgalloc_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgalloc_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgalloc_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgalloc_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgalloc_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    },
    {
     "title": "Refill",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgrefill_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgrefill_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgrefill_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgrefill_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgrefill_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgrefill_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgrefill_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgrefill_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    },
    {
     "title": "Direct Scan",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgscan_direct_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_direct_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgscan_direct_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_direct_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgscan_direct_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_direct_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgscan_direct_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_direct_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    },
    {
     "title": "Kswapd Scan",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgscan_kswapd_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_kswapd_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgscan_kswapd_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_kswapd_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgscan_kswapd_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_kswapd_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgscan_kswapd_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgscan_kswapd_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    },
    {
     "title": "Steal Direct",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgsteal_direct_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_direct_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_direct_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_direct_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_direct_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_direct_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_direct_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_direct_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    },
    {
     "title": "Steal Kswapd",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgsteal_kswapd_dma{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_kswapd_dma{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_kswapd_dma32{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_kswapd_dma32{node_name=~\"$host\"}[5m])",
       "legendFormat": "Dma32"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_kswapd_normal{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_kswapd_normal{node_name=~\"$host\"}[5m])",
       "legendFormat": "Normal"
      },
      {
       "expr": "rate(node_vmstat_pgsteal_kswapd_movable{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgsteal_kswapd_movable{node_name=~\"$host\"}[5m])",
       "legendFormat": "Movable"
      }
     ]
    }
   ]
  }
 ]
}