{
 "title": "MongoDB WiredTiger",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",engine=\"wiredTiger\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\",node_name=~\"$host\",engine=\"wiredTiger\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "description": "This panel shows the amount of data currently stored in the WiredTiger cache. This data is in its uncompressed format and differs from how the data is stored on disk or in the file system cache. This value will always be lower than the counter shown in the *WiredTiger Max Cache Size* panel.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{service_name=\"$service\", type=\"total\"}"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "description": "This is the maximum size that the WiredTiger cache can grow to and can be changed from the default value by setting the `storage.wiredTiger.engineConfig.cacheSizeGB` value in the config file or passing in the `--wiredTigerCacheSizeGB` parameter on the command line.\n\nYou can read more about [setting the WiredTiger maximum cache size](https://docs.mongodb.com/manual/reference/configuration-options/#storage.wiredTiger.engineConfig.cacheSizeGB).",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "description": "This is the amount of the file system memory in use.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "pmm-singlestat-panel",
   "description": "This panel shows how much of the system memory is free.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "description": "This panel shows statistics about the WiredTiger transactions operations and checkpoints over the given interval.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "description": "This panel shows activity in WiredTiger cache for the given period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=\"$service\", type=\"read\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=\"$service\", type=\"read\"}[5m])",
     "legendFormat": "Read into"
    },
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=\"$service\", type=\"written\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{service_name=\"$service\", type=\"written\"}[5m])",
     "legendFormat": "Written from"
    }
   ]
  },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "description": "This panel shows the number of bytes that the WiredTiger block manager has processed over the given interval.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "description": "This panel shows information about the currently open WiredTiger sessions and cursors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{service_name=\"$service\"}",
     "legendFormat": "Cursors"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_sessions_total{service_name=\"$service\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "description": "This panel shows the number of concurrent tickets available for reads and writes. These values are user configurable so you can tune read and write heavy applications as appropriate.\n\nLearn how to configure [WiredTiger concurrency tickets](https://docs.mongodb.com/manual/reference/parameters/#wiredtiger-parameters).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{service_name=\"$service\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{service_name=\"$service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{service_name=\"$service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "description": "This panel shows the number of WiredTiger checkpoints that are currently running and how long they are taking.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{service_name=\"$service\"}[5m])",
     "legendFormat": "current"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{service_name=\"$service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "description": "This panel shows the number of pages that have been evicted from the WiredTiger cache for the given time period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Capacity",
   "type": "graph",
   "description": "This panel shows a graphical representation of the *WiredTiger Cache Usage* and *WiredTiger Max Cache Size* at the top of this worksheet.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{service_name=\"$service\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{service_name=\"$service\", type=\"total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "description": "This panel shows the number of pages in the WiredTiger cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{service_name=\"$service\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "description": "This panel shows information about the number of operations performed on the WiredTiger write ahead log.\n\nLearn more about the [WiredTiger journal](https://docs.mongodb.com/manual/core/journaling/#journaling-and-the-wiredtiger-storage-engine).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Activity",
   "type": "graph",
   "description": "This panel shows information about the amount of data that has been written to the WiredTiger write ahead log.\n\nLearn more about the [WiredTiger journal](https://docs.mongodb.com/manual/core/journaling/#journaling-and-the-wiredtiger-storage-engine).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_bytes_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "description": "This panel shows information about the number of records written to the WiredTiger write ahead log. If the log record is less than 128 bytes it will not be compressed.\n\nLearn more about the [WiredTiger journal](https://docs.mongodb.com/manual/core/journaling/#journaling-and-the-wiredtiger-storage-engine).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_log_records_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "description": "This panel shows the average number of documents changed per second for the given time period. These changes are broken out by `update`, `delete` and `insert`. If this is a secondary node, then it will show the number of replicated commands.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=\"$service\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=\"$service\"}[5m])",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "description": "This panel shows the number of objects (both data (*scanned_objects*) and index (*scanned*)). If the number of *scanned_objects* is much higher than the number for *scanned* check to make sure you have indexes to support your queries. Generally you want to see a higher value for *scanned* than for *scanned_objects*.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{service_name=\"$service\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Page faults indicate that requests are being processed from disk rather than from memory. This is due to there not being enough memory for the current working set. A low number here isn't generally a concern, but if this counter is consistently high, first check to make sure you have indexes on your collections to support the queries you normally run. If the counter stays high, you should consider increasing the server's memory or look into sharding your database.\n\nYou can read more about [Page Faults](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/#page-faults).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{service_name=\"$service\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{service_name=\"$service\"}[5m]) or rate(mongodb_extra_info_page_faults_total{service_name=\"$service\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{service_name=\"$service\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}