{
 "title": "MongoDB ReplSet",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\", set=\"$replset\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\",node_name=~\"$host\",set=\"$replset\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "ReplSet State",
   "type": "singlestat",
   "description": "This shows the role of the selected instance. Normally this should be one of ``PRIMARY``, ``SECONDARY`` and ``ARBITER``, but if the system is newly added it could show ``STARTUP2`` during its initial sync.\n\nRead more about [Replica Set Member States](https://docs.mongodb.com/manual/reference/replica-states/).",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "singlestat",
   "description": "This shows how many members are configured in the replica set.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "singlestat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "singlestat",
   "description": "This panel shows how far behind in replication this member is if it is a secondary. This number may be high it the instance is running as a delayed secondary member.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\", set=\"$replset\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"} * on (name) group_left mongodb_mongod_replset_my_name{service_name=~\"$service\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Storage Engine",
   "type": "singlestat",
   "description": "This shows which storage engine the instance is configured with.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "mongodb_mongod_storage_engine{service_name=~\"$service\"}",
     "legendFormat": "{{ engine }}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "description": "This shows the number of replicated commands that have been sent from the primary to this instance. This will always be empty on a primary instance.\n\n*NOTE*: A single command (such as a call to `.updateMany()`) on the primary can generate multiple replicated commands on a secondary.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|getmore|query)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service\", type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "description": "This shows how much time the oplog covers. The oplog is a capped (fixed size) collection and the amount of time can grow or shrink as workloads decrease or increase. You want to make sure the oplog is sized big enough to handle the time it takes for maintenance or to sync a secondary member.\n\nLearn more about the [Oplog](https://docs.mongodb.com/manual/core/replica-set-oplog/).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service\"}",
     "legendFormat": "Now to End"
    },
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{service_name=~\"$service\"}-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service\"}",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "This shows the amount of time that a secondary is behind the primary. A high value could be due the secondary being delayed. If this instance is a normal secondary you will want to check the instance to determine why it is behind and resolve the issue.\n\nLearn more about [Replication Lag](https://docs.mongodb.com/manual/tutorial/troubleshoot-replica-sets/#replica-set-replication-lag).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\", set=\"$replset\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"} * on (name) group_left mongodb_mongod_replset_my_name{service_name=~\"$service\"})) or vector(0)",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "description": "This shows when elections occur in the replica set. An election happens whenever the primary instance is not accessible to the rest of the members. Looking at this graph over long periods of time can help you to correlate elections to other system events.\n\nLearn more about [Replica set Elections](https://docs.mongodb.com/manual/core/replica-set-elections/).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{service_name=~\"$service\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "description": "This graph shows all replica set members and the amount of time that each member was in a given state.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{service_name=~\"$service\"}\n* on (name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name[$interval]) or max_over_time(mongodb_mongod_replset_my_name[5m]))",
     "legendFormat": "{{ instance }} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "description": "This chart shows the heartbeat time between this instance and all other instances in the replica set. If there is no heartbeat returned after 10 seconds the node in considered to be unreachable and would require intervention to determine the cause.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{service_name=~\"$service\"}) by (name) * on (name) group_right mongodb_mongod_replset_my_name",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "description": "This shows the number of milliseconds that a round-trip packet required when communication with other members of the replica set. High values could indicate an issue such as network lag and should be looked into.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{service_name=~\"$service\"}\n* on (name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name[$interval]) or max_over_time(mongodb_mongod_replset_my_name[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "description": "This is the number of milliseconds that the secondary member spends in getting receiving data from the instance it's replicating from.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{service_name=~\"$service\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "description": "This shows the number of operations per second that the secondary member is receiving from its source.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_num_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_ops_total{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{service_name=~\"$service\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "description": "This shows the amount of time it takes a secondary instance to apply data from the oplog.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{service_name=~\"$service\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{service_name=~\"$service\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{service_name=~\"$service\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{service_name=~\"$service\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "description": "This shows the number of operations that are in the oplog buffer waiting to be applied on the secondary member.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_count{service_name=~\"$service\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "description": "This shows the maximum size of the oplog buffer and the current amount of data being stored in the buffer. The maximum size is not configurable currently and is set by the `mongod` process.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{service_name=~\"$service\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{service_name=~\"$service\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}