{
 "title": "MySQL InnoDB Compression",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mysql_up{node_name=~\"$host\"}, service_name)"
   },
   {
    "name": "buffer",
    "query": "label_values(mysql_info_schema_innodb_cmpmem_pages_used_total,buffer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Compression level and failure rate threshold",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "InnoDB Compression level",
   "type": "singlestat",
   "description": "The level of zlib compression to use for InnoDB compressed tables and indexes.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_compression_level{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "InnoDB Compression Failure Threshold",
   "type": "singlestat",
   "description": "The compression failure rate threshold for a table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_compression_failure_threshold_pct{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "Compression Failure Rate Threshold",
   "type": "singlestat",
   "description": "The maximum percentage that can be reserved as free space within each compressed page, allowing room to reorganize the data and modification log within the page when a compressed table or index is updated and the data might be recompressed.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_compression_pad_pct_max{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "Write Pages to The Redo Log",
   "type": "singlestat",
   "description": "Specifies whether images of re-compressed pages are written to the redo log. Re-compression may occur when changes are made to compressed data.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_log_compressed_pages{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "Statistic of compression operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Compress Attempts",
   "type": "graph",
   "description": "Number of compression operations attempted. Pages are compressed whenever an empty page is created or the space for the uncompressed modification log runs out.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_cmp_compress_ops_total{service_name=\"$service\"}[$interval]) or irate(mysql_info_schema_innodb_cmp_compress_ops_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  {
   "title": "Uncompressed Attempts",
   "type": "graph",
   "description": "Number of uncompression operations performed. Compressed InnoDB pages are uncompressed whenever compression fails, or the first time a compressed page is accessed in the buffer pool and the uncompressed page does not exist.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_info_schema_innodb_cmp_uncompress_ops_total{service_name=\"$service\"}[$interval]) or \nirate(mysql_info_schema_innodb_cmp_uncompress_ops_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  {
   "title": "Compression Success Ratio",
   "type": "graph",
   "description": "Shows the ratio between Success InnoDB Compress vs the total InnoDB Compress operations. A high ration indicates that InnoDB compression is being effective and helping to save disk space.\n\nSee also:",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{service_name=\"$service\"}[$interval])/\nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{service_name=\"$service\"}[$interval]) or \nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_ok_total{service_name=\"$service\"}[5m])/\nsum_over_time(mysql_info_schema_innodb_cmp_compress_ops_total{service_name=\"$service\"}[5m])",
     "legendFormat": "{{ page_size }}"
    }
   ]
  },
  { "title": "CPU Core Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Core Usage for Compression",
   "type": "graph",
   "description": "Shows the time in seconds spent by InnoDB Compression operations.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(mysql_info_schema_innodb_cmp_compress_time_seconds_total{instance=~\"$host\"}[$interval])) by (instance) or\nsum(irate(mysql_info_schema_innodb_cmp_compress_time_seconds_total{instance=~\"$host\"}[5m])) by (instance)) /\ncount(node_cpu_seconds_total{mode=\"user\", instance=~\"$host\"}) by (instance) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Core Usage for Uncompression",
   "type": "graph",
   "description": "Shows the time in seconds spent by InnoDB Uncompression operations.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(mysql_info_schema_innodb_cmp_uncompress_time_seconds_total{instance=~\"$host\"}[$interval])) by (instance) or\nsum(irate(mysql_info_schema_innodb_cmp_uncompress_time_seconds_total{instance=~\"$host\"}[5m])) by (instance)) /\ncount(node_cpu_seconds_total{mode=\"user\", instance=~\"$host\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Buffer Pool Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Used Pages",
   "type": "graph",
   "description": "Shows the total amount of used compressed pages into the InnoDB Buffer Pool split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(page_size) (mysql_info_schema_innodb_cmpmem_pages_used_total{service_name=\"$service\"})",
     "legendFormat": "{{page_size}}"
    }
   ]
  },
  {
   "title": "Total Free Pages",
   "type": "graph",
   "description": "Shows the total amount of free compressed pages into the InnoDB Buffer Pool split by page size.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(page_size) (mysql_info_schema_innodb_cmpmem_pages_free_total{service_name=\"$service\"})",
     "legendFormat": "{{page_size}}"
    }
   ]
  },
  {
   "title": "Buffer Pool  $buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "buffer",
   "collapsed": true,
   "panels": [
    {
     "title": "Used Pages (Buffer Pull $buffer)",
     "type": "graph",
     "description": "Shows the amount of used compressed pages into this InnoDB Buffer Pool instance split by page size.\n\nSee also:",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_info_schema_innodb_cmpmem_pages_used_total{service_name=\"$service\",buffer=~\"$buffer\"}",
       "legendFormat": "{{page_size}}"
      }
     ]
    },
    {
     "title": "Pages Free (Buffer Pull $buffer)",
     "type": "graph",
     "description": "Shows the amount of free compressed pages into this InnoDB Buffer Pool instance split by page size.\n\nSee also:",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_info_schema_innodb_cmpmem_pages_free_total{service_name=\"$service\",buffer=\"$buffer\"}",
       "legendFormat": "{{page_size}}"
      }
     ]
    }
   ]
  }
 ]
}