{
 "title": "Prometheus Exporters Overview",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(process_start_time_seconds{node_name=~\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Exporters Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg CPU Usage per Host",
   "type": "pmm-singlestat-panel",
   "description": "Shows the average CPU usage in percent per host for all exporters. An Exporter is a software library that provides metrics to PMM.\n\nNote that the CPU usage is only the CPU usage of the exporter itself. It does not include the additional resource usage that is required to produce metrics by the application or operating system.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((sum(rate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[$interval])) by (node_name) or \nsum(irate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[5m])) by (node_name)) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=~\"$host\"}) by (node_name)) by ()*100"
    }
   ]
  },
  {
   "title": "Avg Memory Usage per Host",
   "type": "singlestat",
   "description": "Shows the Exporters average Memory usage per host. An Exporter is a software library that provides metrics to PMM.\n\nNote that the Memory usage is only the Memory usage of the exporter itself. It does not include the additional memory usage that is required to produce metrics by the application or operating system.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(sum(process_resident_memory_bytes{job=~\".*exporter.*\",node_name=~\"$host\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Monitored Hosts",
   "type": "singlestat",
   "description": "Shows the number of monitored hosts that are running Exporters. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(count(process_open_fds{job=~\".*exporter.*\",node_name=~\"$host\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "singlestat",
   "description": "Shows the total number of Exporters running with this PMM Server instance. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(process_open_fds{job=~\".*exporter.*\",node_name=~\"$host\"}) "
    }
   ]
  },
  {
   "title": "Prometheus Exporters Resource Usage by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Plots the Exporters' CPU usage across each monitored host (by default, All hosts). An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[$interval])) by (node_name) or \nsum(irate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[5m])) by (node_name)) / \ncount(node_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}) by (node_name) *100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Plots the Exporters' Memory usage across each monitored host (by default, All hosts). An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\".*exporter.*\",node_name=~\"$host\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Prometheus Resource usage by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "CPU Cores Used",
   "type": "graph",
   "description": "Shows the Exporters' CPU Cores used for each type of Exporter. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg(rate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[$interval])) by (agent_type) or \navg(irate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[5m])) by (agent_type))",
     "legendFormat": "{{agent_type}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the Exporters' memory used for each type of Exporter. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=~\".*exporter.*\",node_name=~\"$host\"}) by (agent_type)",
     "legendFormat": "{{agent_type}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "host" },
  { "title": "Host", "type": "text", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 }, "content": "$host" },
  {
   "title": "CPU  Used",
   "type": "pmm-singlestat-panel",
   "description": "Show the CPU usage as a percentage for all Exporters on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(rate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[$interval])) by (node_name) \nor sum(irate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$host\"}[5m])) by (node_name)) \n/ count(node_cpu_seconds_total{node_name=~\"$host\",mode=\"user\"}) by (node_name)*100) or \nsum by () ((max_over_time(node_cpu_average{node_name=~\"$host\", mode=\"total\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$host\", mode=\"total\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "singlestat",
   "description": "Shows total Memory Used by Exporters on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(process_resident_memory_bytes{job=~\".*exporter.*\",node_name=~\"$host\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "singlestat",
   "description": "Shows the number of Exporters running on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(process_open_fds{job=~\".*exporter.*\",node_name=~\"$host\"}) "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "count(process_cpu_seconds_total{node_name=~\"$host\"}) by (agent_type)"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "description": "Shows the total number of virtual CPUs on the host. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "description": "Shows the total amount of RAM of the host. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_open_fds{node_name=~\"$host\"})"
    }
   ]
  }
 ]
}