{
 "title": "Prometheus Exporter Status",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\", node_name=\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(process_cpu_seconds_total{node_name=~\"$host\",job=~\"node_exporter_.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=~\"$host\",job=~\"node_exporter_.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_resident_memory_bytes{node_name=\"$host\",job=~\"node_exporter_.*\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_open_fds{node_name=\"$host\",job=~\"node_exporter_.*\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - process_start_time_seconds{node_name=\"$host\",job=~\"node_exporter_.*\"}"
    }
   ]
  },
  {
   "title": "Collector Scrape Successful",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "min_over_time(node_scrape_collector_success{node_name=~\"$host\"}[$interval]) or \nmin_over_time(node_scrape_collector_success{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector Execution Time  (Log Scale)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$host\"}[$interval]) or \navg_over_time(node_scrape_collector_duration_seconds{node_name=\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    },
    {
     "expr": "sum(avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$host\"}[$interval])) or \nsum(avg_over_time(node_scrape_collector_duration_seconds{node_name=\"$host\"}[5m]))",
     "legendFormat": "Total Load"
    }
   ]
  },
  {
   "title": "MySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(process_open_fds{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter.*\"})"
      }
     ]
    },
    {
     "title": "Collector Execution Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mysql_exporter_collector_duration_seconds{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \navg_over_time(mysql_exporter_collector_duration_seconds{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "{{collector}} - {{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mysql_exporter_hr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_exporter_hr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "High Resolution - {{service_name}}"
      },
      {
       "expr": "max_over_time(mysql_exporter_mr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_exporter_mr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "Medium Resolution {{service_name}}"
      },
      {
       "expr": "max_over_time(mysql_exporter_lr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nmax_over_time(mysql_exporter_lr_last_scrape_error{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "Low Resolution - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(mysql_exporter_hr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nirate(mysql_exporter_hr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "High Resolution - {{service_name}}"
      },
      {
       "expr": "rate(mysql_exporter_mr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nirate(mysql_exporter_mr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "Medium Resolution - {{service_name}}"
      },
      {
       "expr": "rate(mysql_exporter_lr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[$interval]) or \nirate(mysql_exporter_lr_scrapes_total{node_name=\"$host\",service_name=~\"$service\"}[5m])",
       "legendFormat": "Low Resolution - {{service_name}}"
      }
     ]
    },
    {
     "title": "MySQL up",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "min_over_time(mysql_up{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter_.*_hr\"}[$interval]) or \nmin_over_time(mysql_up{node_name=\"$host\",service_name=~\"$service\",job=~\"mysqld_exporter_.*_hr\"}[5m])",
       "legendFormat": "MySQL Up - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$host\",service_name=\"~$service\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"})"
      }
     ]
    },
    {
     "title": "MongoDB Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mongodb_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[$interval]) or\navg_over_time(mongodb_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[5m])",
       "legendFormat": "Avg Scrape Time - {{service_name}}"
      }
     ]
    },
    {
     "title": "MongoDB Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mongodb_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[$interval]) or \nmax_over_time(mongodb_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[5m])",
       "legendFormat": "MongoDB Exporter Errors  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(mongodb_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[$interval]) or \nirate(mongodb_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"mongodb.*\"}[5m])",
       "legendFormat": "Scrapes Rate  - {{service_name}}"
      }
     ]
    },
    {
     "title": "MongoDB up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(mongodb_up{node_name=\"$host\",service_name=\"$service\",job=~\"mongodb.*\"}[$interval]) or \nmin_over_time(mongodb_up{node_name=\"$host\",service_name=\"$service\",job=~\"mongodb.*\"}[5m])",
       "legendFormat": "MongoDB Up"
      }
     ]
    }
   ]
  },
  {
   "title": "ProxySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"})"
      }
     ]
    },
    {
     "title": "ProxySQL Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(proxysql_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[$interval]) or \navg_over_time(proxysql_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[5m])",
       "legendFormat": "Avg Scrape Time  - {{service_name}}"
      }
     ]
    },
    {
     "title": "ProxySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(proxysql_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[$interval]) or \nmax_over_time(proxysql_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[5m])",
       "legendFormat": "ProxySQL Exporter Errors  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(proxysql_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[$interval]) or \nirate(proxysql_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[5m])",
       "legendFormat": "Scrapes Rate - {{service_name}}"
      }
     ]
    },
    {
     "title": "ProxySQL up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "min_over_time(proxysql_up{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[$interval]) or \nmin_over_time(proxysql_up{node_name=\"$host\",service_name=~\"$service\",job=~\"proxysql.*\"}[5m])",
       "legendFormat": "ProxySQL Up  - {{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[5m])) by ()) / \ncount(node_cpu_seconds_total{mode=\"user\",node_name=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_resident_memory_bytes{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 35 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum(process_open_fds{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 35 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - avg(process_start_time_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"})"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(pg_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[$interval]) or \nirate(pg_exporter_scrapes_total{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[5m])",
       "legendFormat": "Total  - {{service_name}}"
      },
      {
       "expr": "max_over_time(pg_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[$interval]) or\nmax_over_time(pg_exporter_last_scrape_error{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[5m])",
       "legendFormat": "Failed  - {{service_name}}"
      }
     ]
    },
    {
     "title": "Scrape Durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(pg_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[$interval]) or\nsum_over_time(pg_exporter_last_scrape_duration_seconds{node_name=\"$host\",service_name=~\"$service\",job=~\"postgres.*\"}[5m])",
       "legendFormat": "Duration  - {{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}